# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUrTNeVDMOv0ktMoPZbaBw9XkAN5EGTN
"""

!pip install sentence-transformers
!pip install spacy
!pip install nltk
!pip install streamlit

!python -m spacy download en_core_web_sm

import spacy
import nltk
import string
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords

from google.colab import files

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

uploaded = files.upload()

with open("freedom_fighters_docs.txt", "r", encoding="utf-8") as f:
    documents = f.read()

print(documents[:500])

sentences = sent_tokenize(documents)

print("Total sentences:", len(sentences))
print(sentences[0])

nlp = spacy.load("en_core_web_sm")

model = SentenceTransformer('all-MiniLM-L6-v2')

sentence_embeddings = model.encode(sentences)

def extract_entities(text):

    doc = nlp(text)

    entities = [(ent.text, ent.label_) for ent in doc.ents]

    return entities

def get_answer(question):

    entities = extract_entities(question)

    question_embedding = model.encode([question])

    similarity = cosine_similarity(question_embedding, sentence_embeddings)

    best_index = similarity.argmax()

    answer = sentences[best_index]

    return answer, entities

while True:

    question = input("\nAsk a question (type 'exit' to stop): ")

    if question.lower() == "exit":
        break

    answer, entities = get_answer(question)

    print("Entities:", entities)
    print("Answer:", answer)