# -*- coding: utf-8 -*-
"""Ques-Ans System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7XwRCxvDnyis7cUHWwwJKISieo8M9XG
"""

!pip install transformers sentence-transformers faiss-cpu torch
!pip install beautifulsoup4 requests pdfplumber python-docx
!pip install nltk accelerate

import torch
import numpy as np
import faiss
import re
import os
import io
import requests
import nltk
import pdfplumber
from bs4 import BeautifulSoup
from sentence_transformers import SentenceTransformer
from transformers import T5ForConditionalGeneration, T5Tokenizer
from google.colab import files
import docx

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab')

print("Loading embedding model...")
embedder = SentenceTransformer('all-mpnet-base-v2')

print("Loading generator...")
t5_tokenizer = T5Tokenizer.from_pretrained('google/flan-t5-large')
t5_model     = T5ForConditionalGeneration.from_pretrained('google/flan-t5-large')

device = 'cuda' if torch.cuda.is_available() else 'cpu'
t5_model = t5_model.to(device)

print(f"✓ Running on {device.upper()}")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FINAL QA SYSTEM — SMART GENERATIVE + SAFE EXTRACTIVE (PRODUCTION VERSION)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import re, io, requests, nltk, faiss, torch
import numpy as np
from bs4 import BeautifulSoup
import pdfplumber, docx

nltk.download('punkt')


# ── CLEAN TEXT ───────────────────────────────────────────────────────────────
def clean_text(text):
    text = re.sub(r'\[[A-Z]\]', '', text)
    text = re.sub(r'[^a-zA-Z0-9.,;:!?()\s%\-\/\']', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


# ── POLISH OUTPUT ────────────────────────────────────────────────────────────
def polish_answer(text):
    text = text.replace(';', ',')
    text = re.sub(r'Risk Factors', 'Risk factors', text)

    sentences = nltk.sent_tokenize(text)
    sentences = [s.strip().capitalize() for s in sentences]

    return " ".join(sentences)


class BERTGenerativeQA:
    def __init__(self, chunk_size=400, top_k=8):
        self.chunk_size = chunk_size
        self.top_k = top_k
        self.chunks = []
        self.index = None
        self.embeddings = None
        self.source_labels = []

    # ── FILE READERS ─────────────────────────────────────────────────────────

    def _read_pdf(self, data):
        text = ""
        with pdfplumber.open(io.BytesIO(data)) as pdf:
            for page in pdf.pages:
                extracted = page.extract_text()
                if extracted:
                    text += extracted + "\n"
        return text

    def _read_docx(self, data):
        doc = docx.Document(io.BytesIO(data))
        return "\n".join(p.text for p in doc.paragraphs)

    def _read_txt(self, data):
        return data.decode('utf-8', errors='ignore')

    def extract_from_url(self, url):
        resp = requests.get(url, timeout=10)
        soup = BeautifulSoup(resp.text, 'html.parser')
        for tag in soup(['script', 'style']):
            tag.decompose()
        return soup.get_text(separator=' ', strip=True)

    # ── CHUNKING ─────────────────────────────────────────────────────────────

    def _chunk_text(self, text):
        sentences = nltk.sent_tokenize(text)
        chunks, chunk = [], []

        for sent in sentences:
            chunk.append(sent)
            if len(" ".join(chunk)) >= self.chunk_size:
                chunks.append(" ".join(chunk))
                chunk = chunk[-2:]

        if chunk:
            chunks.append(" ".join(chunk))

        return chunks

    # ── BUILD INDEX ──────────────────────────────────────────────────────────

    def build_index(self, text_dict):
        self.chunks, self.source_labels = [], []

        print("Processing documents...")
        for source, text in text_dict.items():
            text = clean_text(text)
            ch = self._chunk_text(text)
            self.chunks += ch
            self.source_labels += [source] * len(ch)
            print(f"{source} → {len(ch)} chunks")

        print("\nEncoding...")
        self.embeddings = embedder.encode(
            self.chunks,
            batch_size=32,
            convert_to_numpy=True,
            show_progress_bar=True
        )

        faiss.normalize_L2(self.embeddings)
        dim = self.embeddings.shape[1]
        self.index = faiss.IndexFlatIP(dim)
        self.index.add(self.embeddings)

        print(f"\n✓ Index ready — {len(self.chunks)} chunks")

    # ── RETRIEVAL ────────────────────────────────────────────────────────────

    def retrieve(self, question):
        expanded = question + " explanation definition causes symptoms effects treatment management"
        q_vec = embedder.encode([expanded], convert_to_numpy=True)
        faiss.normalize_L2(q_vec)

        scores, indices = self.index.search(q_vec, self.top_k)

        results = []
        for score, idx in zip(scores[0], indices[0]):
            if 0 <= idx < len(self.chunks) and float(score) >= 0.35:
                results.append({
                    "chunk": self.chunks[idx],
                    "score": float(score),
                    "source": self.source_labels[idx]
                })

        results = sorted(results, key=lambda x: x["score"], reverse=True)

        if not results:
            idx = int(indices[0][0])
            results.append({
                "chunk": self.chunks[idx],
                "score": float(scores[0][0]),
                "source": self.source_labels[idx]
            })

        return results

    # ── EXTRACTIVE SAFE ANSWER ───────────────────────────────────────────────

    def _extractive_answer(self, question, context):
        sentences = nltk.sent_tokenize(context)

        sent_emb = embedder.encode(sentences, convert_to_numpy=True)
        q_emb = embedder.encode([question], convert_to_numpy=True)

        faiss.normalize_L2(sent_emb)
        faiss.normalize_L2(q_emb)

        scores = np.dot(sent_emb, q_emb.T).flatten()
        ranked = scores.argsort()[::-1]

        selected = []
        seen = set()

        for i in ranked:
            sent = sentences[i]
            sent_lower = sent.lower()

            key = re.sub(r'[^a-z0-9]', '', sent_lower)
            if key in seen:
                continue
            seen.add(key)

            if scores[i] < 0.3:
                continue

            if len(sent.split()) < 6:
                continue

            if "diabetes" in sent_lower and "hypertension" in question.lower():
                continue

            if "another major" in sent_lower:
                continue

            selected.append(sent)

            if len(selected) >= 5:
                break

        return " ".join(selected)

    # ── GENERATION + SMART DECISION ──────────────────────────────────────────

    def generate_answer(self, question, context_chunks):
        full_context = " ".join(c['chunk'] for c in context_chunks)

        prompt = (
            "Answer using the context.\n\n"
            f"Context:\n{full_context}\n\n"
            f"Question: {question}\nAnswer:"
        )

        inputs = t5_tokenizer(
            prompt,
            return_tensors='pt',
            truncation=True,
            max_length=1024
        ).to(device)

        with torch.no_grad():
            outputs = t5_model.generate(
                **inputs,
                max_new_tokens=150,
                num_beams=4
            )

        generated = t5_tokenizer.decode(outputs[0], skip_special_tokens=True)
        print("\n[T5 RAW OUTPUT]:", generated)

        extractive = self._extractive_answer(question, full_context)

        # ── SMART CHOICE ───────────────────────────────
        gen_lower = generated.lower()
        context_lower = full_context.lower()

        overlap = sum(1 for w in gen_lower.split() if w in context_lower)

        if overlap >= 5:
            final_answer = generated
        else:
            final_answer = extractive

        # ── INTENT FILTER ─────────────────────────────
        q = question.lower()
        sentences = nltk.sent_tokenize(final_answer)

        if any(word in q for word in ["how", "manage", "treat"]):
            filtered = []
            for s in sentences:
                if any(w in s.lower() for w in ["manage", "diet", "therapy", "exercise", "insulin", "lifestyle"]):
                    filtered.append(s)

            if filtered:
                return polish_answer(" ".join(filtered))

        return polish_answer(final_answer)

    # ── ASK ──────────────────────────────────────────────────────────────────

    def ask(self, question, verbose=False):
        retrieved = self.retrieve(question)
        answer = self.generate_answer(question, retrieved)

        if verbose:
            print("\n--- DEBUG ---")
            for r in retrieved:
                print(f"{r['score']:.3f} [{r['source']}]")
                print(r['chunk'][:120], "\n")

        return answer, retrieved


# ── INIT ─────────────────────────────────────────────────────────────────────
qa_system = BERTGenerativeQA(chunk_size=400, top_k=8)
def ask_with_trace(qa_system, question):
    print("\n================= QA PIPELINE TRACE =================\n")

    # STEP 1
    print("🔹 STEP 1: User Question")
    print("→ The question entered by the user")
    print(question)

    # STEP 2
    expanded = question + " explanation definition causes symptoms effects treatment management"
    print("\n🔹 STEP 2: Query Expansion")
    print("→ Expanding question to improve retrieval")
    print(expanded)

    # STEP 3
    print("\n🔹 STEP 3: Retrieval")
    print("→ Finding most relevant text chunks using embeddings (FAISS)")
    retrieved = qa_system.retrieve(question)

    for i, r in enumerate(retrieved):
        print(f"\nChunk {i+1} | Score: {r['score']:.3f}")
        print(r['chunk'][:200])

    # STEP 4
    full_context = " ".join([c['chunk'] for c in retrieved])
    print("\n🔹 STEP 4: Context Creation")
    print("→ Combining retrieved chunks into a single context")
    print(full_context[:500])

    # STEP 5
    print("\n🔹 STEP 5: Generative Model (T5)")
    print("→ Model generates answer based on context")

    prompt = (
        "Answer using the context.\n\n"
        f"Context:\n{full_context}\n\n"
        f"Question: {question}\nAnswer:"
    )

    inputs = t5_tokenizer(prompt, return_tensors='pt', truncation=True, max_length=1024).to(device)

    with torch.no_grad():
        outputs = t5_model.generate(**inputs, max_new_tokens=150, num_beams=4)

    generated = t5_tokenizer.decode(outputs[0], skip_special_tokens=True)
    print("T5 Output:", generated)

    # STEP 6
    print("\n🔹 STEP 6: Extractive Answer")
    print("→ Extracting most relevant sentences directly from context")
    extractive = qa_system._extractive_answer(question, full_context)
    print(extractive)

    # STEP 7
    print("\n🔹 STEP 7: Answer Selection")
    print("→ Choosing between T5 output and extractive answer")

    overlap = sum(1 for w in generated.lower().split() if w in full_context.lower())
    print("Overlap score:", overlap)

    if overlap >= 5:
        final_answer = generated
        print("Using T5 Answer")
    else:
        final_answer = extractive
        print("Using Extractive Answer")

    # STEP 8
    print("\n🔹 STEP 8: Final Answer Processing")
    print("→ Filtering answer based on question type (e.g., how/what)")

    q = question.lower()
    sentences = nltk.sent_tokenize(final_answer)

    if any(word in q for word in ["how", "manage", "treat"]):
        filtered = []
        for s in sentences:
            if any(w in s.lower() for w in ["manage", "diet", "therapy", "exercise", "insulin", "lifestyle"]):
                filtered.append(s)

        if filtered:
            final_answer = " ".join(filtered)

    final_answer = polish_answer(final_answer)

    print("\n🔹 FINAL ANSWER")
    print(final_answer)

    print("\n================= END =================\n")

    return final_answer

qa_system = BERTGenerativeQA()

uploaded = files.upload()
text_dict = {}

for filename, file_bytes in uploaded.items():
    ext = os.path.splitext(filename)[1].lower()

    if ext == '.pdf':
        text = qa_system._read_pdf(file_bytes)
    elif ext == '.docx':
        text = qa_system._read_docx(file_bytes)
    else:
        text = qa_system._read_txt(file_bytes)

    text_dict[filename] = text
    print(f"{filename} loaded")

qa_system.build_index(text_dict)

question = "what is hypertension?"

answer = ask_with_trace(qa_system, question)

print("\nAnswer:\n", answer)